version: '3.8'

services:
  
  postgres_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - project_db:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend/
    depends_on:
      - postgres_db
    ports:
      - 8080:8080
    restart: always
  
  frontend:
    build:
      context: ./frontend_backup/
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: always

volumes:
  project_db: 