version: '3.8'

services:
  
  postgres_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - project_db:/var/lib/postgresql/data

volumes:
  project_db: 